// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// URLRemover is an autogenerated mock type for the URLRemover type
type URLRemover struct {
	mock.Mock
}

// DeleteURL provides a mock function with given fields: ctx, alias
func (_m *URLRemover) DeleteURL(ctx context.Context, alias string) error {
	ret := _m.Called(ctx, alias)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, alias)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewURLRemover interface {
	mock.TestingT
	Cleanup(func())
}

// NewURLRemover creates a new instance of URLRemover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewURLRemover(t mockConstructorTestingTNewURLRemover) *URLRemover {
	mock := &URLRemover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
